name: Test And Build
on: [push]
jobs:
  setup-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing
        run: npm ci
      - name: Testing
        run: npm test
      - name: Building
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-build-root
  test-capacitor-android:
    needs: setup-test-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: web-build-root
      - name: Copy to native apps
        run: npx cap copy
      - name: Update Android Dependencies
        run: npx cap update android
